AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'spec/spec_helper.rb'
    - 'spec/fixtures/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 3.0
  SuggestExtensions:
    rubocop-rake: false

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Description: 'Limit lines to 160 characters.'
  Max: 160
  IgnoredPatterns: [ '\A#' ]

Style/DateTime:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/CyclomaticComplexity:
  Max: 10