AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'spec/spec_helper.rb'
    - 'spec/fixtures/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.7

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 40

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  ExcludedMethods: []
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Description: 'Limit lines to 80 characters.'
  Max: 160
  IgnoredPatterns: ['\A#']

Style/DateTime:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/CyclomaticComplexity:
  Max: 10